build:
    nodes:
        analysis:
            dependencies:
                after:
                    - git clone https://github.com/pimcore/pimcore
                    - cd ./pimcore
                    - git reset --hard b132bb1b89d2b0318a188769aba0bc4e509dfa2f
                    - composer install
                    - cd ../

            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - js-scrutinizer-run
checks:
    php: true
coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
filter:
    dependency_paths:
        - pimcore/
    excluded_paths:
        - tests/
        - src/ToolboxBundle/Resources/public/js/frontend/vendor
        - docs/