pimcore:
    documents:
        tags:
            map:
                googlemap: \ToolboxBundle\Model\Document\Tag\GoogleMap
                parallaximage: \ToolboxBundle\Model\Document\Tag\ParallaxImage
                vhs: \ToolboxBundle\Model\Document\Tag\Vhs
                globallink: \ToolboxBundle\Model\Document\Tag\GlobalLink