toolbox:
    ckeditor:
        global_style_sets:
            default:
              - name: Button Default
                element: a
                attributes:
                    class: btn btn-default