services:
    toolbox.area.brick.anchor:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Anchor\Anchor
        tags:
            - { name: pimcore.area.brick, id: anchor }
toolbox:
    areas:
        anchor:
            config_elements:
                anchor_name:
                    type: input
                    title: 'Anchor Name'
                    config: ~
                anchor_title:
                    type: input
                    title: 'Anchor Title'
                    config: ~
