services:
    toolbox.area.brick.anchor:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Anchor\Anchor
        tags:
            - { name: pimcore.area.brick, id: anchor }
toolbox:
    areas:
        anchor:
            configElements:
                anchorName:
                    type: input
                    title: Anchor Name
                    config: ~
                anchorTitle:
                    type: input
                    title: Anchor Title
                    config: ~
