services:
    ToolboxBundle\Document\Areabrick\Anchor\Anchor:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        autowire: true
        tags:
            - { name: pimcore.area.brick, id: anchor }
toolbox:
    areas:
        anchor:
            config_elements:
                anchor_name:
                    type: input
                    title: 'Anchor Name'
                    config: ~
                anchor_title:
                    type: input
                    title: 'Anchor Title'
                    config: ~