toolbox:
    areas:
        columns:
            configElements:
                type:
                    type: select
                    config:
                        title: Columns
                        values:
                            column_12: 1 Column
                            column_4_8: 2 Columns (33:66)
                            column_8_4: 2 Columns (66:33)
                            column_3_9: 2 Columns (25:75)
                            column_9_3: 2 Columns (75:25)
                            column_6_6: 2 Columns (50:50)
                            column_4_4_4: 3 Columns (33:33:33)
                        default: column_12
                equalHeight:
                    type: checkbox
                    config:
                        title: Equal heights?
                        reload: false