services:
    ToolboxBundle\Document\Areabrick\Content\Content:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - { name: pimcore.area.brick, id: content }
toolbox:
    areas:
        content:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~