services:
    toolbox.area.brick.content:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Content\Content
        tags:
            - { name: pimcore.area.brick, id: content }
toolbox:
    areas:
        content:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~