toolbox:
    areas:
        container:
            configElements:
                fullWidthContainer:
                    type: checkbox
                    config:
                        title: Fluid Container (Full Width)
                        reload: true