services:
    toolbox.area.brick.download:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Download\Download
        arguments:
            - '@toolbox.connector.bundle'
        tags:
            - { name: pimcore.area.brick, id: download }
toolbox:
    areas:
        download:
            config_elements:
                downloads:
                    type: multihref
                    title: Files
                    config:
                        reload: true
                show_preview_images:
                    type: checkbox
                    title: Show preview images
                    config:
                        reload: false
                show_file_info:
                    type: checkbox
                    title: Show file info
                    config:
                        reload: false
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            config_parameter:
                # event_tracker:
                    # category: 'PDF'
                    # action: 'download'
                    # label: ['getMetadata', ['name']]
                    # noninteraction: true