services:
    toolbox.area.brick.download:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Download\Download
        tags:
            - { name: pimcore.area.brick, id: download }
toolbox:
    areas:
        download:
            configElements:
                downloads:
                    type: multihref
                    config:
                        title: Files
                        reload: true
                showPreviewImages:
                    type: checkbox
                    config:
                        title: Show preview images
                        reload: false
                showFileInfo:
                    type: checkbox
                    config:
                        title: Show file info
                        reload: false
                additionalClasses:
                    type: additionalClasses
                    config:
                        values: []
            configParameter:
                # eventTracker:
                    # category: 'PDF'
                    # action: 'download'
                    # label: ['getMetadata', ['name']]
                    # noninteraction: true