services:
    toolbox.area.brick.gallery:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Gallery\Gallery
        tags:
            - { name: pimcore.area.brick, id: gallery }
toolbox:
    areas:
        gallery:
            configElements:
                images:
                    type: multihref
                    title: Images or Folder
                    config:
                        reload: true
                useLightbox:
                    type: checkbox
                    title: Use Lightbox
                    config:
                        reload: false
                useThumbnails:
                    type: checkbox
                    title: Use Thumbnails
                    config:
                        reload: false
                additionalClasses:
                    type: additionalClasses
                    config:
                        store: ~