parameters:
    google_maps_host_url: 'https://maps.google.ch'

services:
    toolbox.area.brick.google_map:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\GoogleMap\GoogleMap
        arguments:
            - '%google_maps_host_url%'
        tags:
            - { name: pimcore.area.brick, id: googleMap }
toolbox:
    areas:
        googleMap:
            configElements:
                mapZoom:
                    type: numeric
                    title: Map zoom
                    config:
                        width: 100
                        minValue: 0
                        maxValue: 19
                        decimalPrecision: 0
                        default: 12
                        reload: false
                mapType:
                    type: select
                    title: Map type
                    config:
                        reload: true
                        store:
                            roadmap: ROADMAP
                            satellite: SATELLITE
                            hybrid: HYBRID
                            terrain: TERRAIN
                        default: roadmap
                iwOnInit:
                    type: checkbox
                    title: Open Info Window by Default
                    config:
                        reload: false
            configParameter:
                mapOptions:
                    streetViewControl: true
                    mapTypeControl: false
                    panControl: false
                    scrollwheel: false
                mapStyleUrl: false
                markerIcon: false