services:
    toolbox.area.brick.image:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Image\Image
        tags:
            - { name: pimcore.area.brick, id: image }
toolbox:
    areas:
        image:
            config_elements:
                use_light_box:
                    type: checkbox
                    title: 'Use Lightbox'
                    col_class: t-col-half
                    config:
                        reload: false
                show_caption:
                    type: checkbox
                    title: 'Display Caption'
                    col_class: t-col-half
                    config:
                        reload: false
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~