services:
    toolbox.area.brick.link_list:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\LinkList\LinkList
        tags:
            - { name: pimcore.area.brick, id: linkList }
toolbox:
    areas:
        linkList:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~