services:
    toolbox.area.brick.linkList:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\LinkList\LinkList
        tags:
            - { name: pimcore.area.brick, id: linkList }
toolbox:
    areas:
        linkList:
            configElements:
                additionalClasses:
                    type: additionalClasses
                    config:
                        store: ~