toolbox:
    areas:
        linkList:
            configElements:
                additionalClasses:
                    type: additionalClasses
                    config:
                        values: []