toolbox:
    areas:
        parallaxContainerSection:
            configElements:
                template:
                    type: select
                    title: Section Template
                    config:
                        reload: true
                        store:
                            no-template: No Template
                        default: no-template
                containerType:
                    type: select
                    title: Section Wrapper Type
                    config:
                        reload: true
                        description: If you need to add some content columns, apply a default or fluid container as wrapper.
                        store:
                            none: No Section Wrapper
                            container: Default Container Wrapper
                            container-fluid: Fluid Container Wrapper
                        default: none
                backgroundImage:
                    type: href
                    title: Background Image
                    config:
                        reload: true
                        types:
                          - asset
                        subtypes:
                            asset:
                              - image
                              - video
                backgroundColor:
                    type: select
                    title: Background Color
                    config:
                        reload: true
                        store:
                            no-background-color: No Background Color
                        default: no-background-color
            configParameter:
                backgroundImageMode: data
                backgroundColorMode: data