services:
    toolbox.area.brick.parallaxContainer:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\ParallaxContainer\ParallaxContainer
        tags:
            - { name: pimcore.area.brick, id: parallaxContainer }
toolbox:
    areas:
        parallaxContainer:
            configElements:
                template:
                    type: select
                    title: Parallax Template
                    config:
                        reload: true
                        store:
                            no-template: No Template
                        default: no-template
                backgroundImage:
                    type: href
                    title: Background Image
                    config:
                        types:
                          - asset
                        subtypes:
                            asset:
                              - image
                              - video
                        reload: true
                backgroundColor:
                    type: select
                    title: Background Color
                    config:
                        reload: true
                        store:
                            no-background-color: No Background Color
                        default: no-background-color
                imageFront:
                    type: parallaximage
                    title: Images In Front Of Main Container
                    config:
                        position:
                            top-left: Top Left
                            top-center: Top Center
                            top-right: Top Right
                            bottom-left: Bottom Left
                            bottom-center: Bottom Center
                            bottom-right: Bottom Right
                            center-left: Center Left
                            center-center: Center Center
                            center-right: Center Right
                        size:
                            half-window-width: Half Window Width
                            third-window-width: Third Window Width
                            quarter-window-width: Quarter Window Width
                        reload: true
                imagesBehind:
                    type: parallaximage
                    title: Images Behind Main Container
                    config:
                        position:
                            top-left: Top Left
                            top-center: Top Center
                            top-right: Top Right
                            bottom-left: Bottom Left
                            bottom-center: Bottom Center
                            bottom-right: Bottom Right
                            center-left: Center Left
                            center-center: Center Center
                            center-right: Center Right
                        size:
                            half-window-width: Half Window Width
                            third-window-width: Third Window Width
                            quarter-window-width: Quarter Window Width
                        reload: true
            configParameter:
                windowSize: large
                backgroundMode: wrap
                backgroundImageMode: data
                backgroundColorMode: data