services:
    toolbox.area.brick.separator:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Separator\Separator
        tags:
            - { name: pimcore.area.brick, id: separator }
toolbox:
    areas:
        separator:
            config_elements:
                space:
                    type: select
                    title: Space before & after separator
                    config:
                        store:
                            default: Default
                            medium: Medium
                            large: Large
                        default: default
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~