services:
    toolbox.area.brick.slide_columns:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\SlideColumns\SlideColumns
        calls:
             - [setCalculator, ['@toolbox.calculator.slide_column_calculator']]
        tags:
            - { name: pimcore.area.brick, id: slideColumns }
toolbox:
    areas:
        slideColumns:
            config_elements:
                slides_per_view:
                    type: select
                    title: 'Slides per View'
                    config:
                        store:
                            '2': '2 Columns'
                            '3': '3 Columns'
                            '4': '4 Columns'
                            '6': '6 Columns'
                        default: '4'
                equal_height:
                    type: checkbox
                    title: 'Equal heights?'
                    config:
                        reload: false
            config_parameter:
                column_classes:
                    '2': col-xs-12 col-sm-6
                breakpoints: []