services:
    toolbox.area.brick.spacer:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Spacer\Spacer
        tags:
            - { name: pimcore.area.brick, id: spacer }
toolbox:
    areas:
        spacer:
            configElements:
                spacerClass:
                    type: select
                    title: Space Class
                    config:
                        reload: false
                        store:
                            spacer-none: No Space
                            spacer-50: 50 Pixel
                        default: spacer-none

                additionalClasses:
                    type: additionalClasses
                    config:
                        store: ~