services:
    toolbox.area.brick.teaser:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Teaser\Teaser
        tags:
            - { name: pimcore.area.brick, id: teaser }
toolbox:
    areas:
        teaser:
            configElements:
                type:
                    type: select
                    title: Type
                    config:
                        name: type
                        store:
                            direct: Direct
                            snippet: Snippet
                        default: direct
                layout:
                    type: select
                    title: Layout
                    conditions:
                        - type: direct
                    config:
                        store:
                            default: Default
                        default: default
                useLightBox:
                    type: checkbox
                    title: use Lightbox?
                    config: ~
                additionalClasses:
                    type: additionalClasses
                    config:
                        store: ~
