services:
    toolbox.area.brick.video:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Video\Video
        tags:
            - { name: pimcore.area.brick, id: video }
toolbox:
    areas:
        video:
            configElements:
                autoplay:
                    type: checkbox
                    title: Autoplay?
                    config:
                        reload: false
                additionalClasses:
                    type: additionalClasses
                    config:
                        store: ~
            configParameter:
                videoTypes:
                    asset:
                        active: false
                    youtube:
                        active: true
                        posterImageThumbnail: null
                    vimeo:
                        active: false
                    dailymotion:
                        active: false