services:
    toolbox.area.brick.video:
        parent: toolbox.area.brick.base_brick
        class: ToolboxBundle\Document\Areabrick\Video\Video
        tags:
            - { name: pimcore.area.brick, id: video }
toolbox:
    areas:
        video:
            config_elements:
                autoplay:
                    type: checkbox
                    title: 'Autoplay?'
                    config:
                        reload: false
                additional_classes:
                    type: additionalClasses
                    config:
                        store: ~
            config_parameter:
                video_types:
                    asset:
                        active: false
                    youtube:
                        active: true
                    vimeo:
                        active: false
                    dailymotion:
                        active: false