services:

    ToolboxBundle\Command\AreaConfigurationCommand:
        autowire: true
        autoconfigure: true
        public: false

    ToolboxBundle\Command\DynamicLinkMigrationCommand:
        autowire: true
        autoconfigure: true
        public: false
