services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # toolbox service layout
    ToolboxBundle\Manager\LayoutManager:
        calls:
            - [setTemplating, ['@templating']]

    # toolbox service area
    ToolboxBundle\Manager\AreaManager: ~

    # toolbox service configuration
    ToolboxBundle\Manager\ConfigManager: ~