services:

    ToolboxBundle\Manager\LayoutManagerInterface: '@ToolboxBundle\Manager\LayoutManager'
    ToolboxBundle\Manager\LayoutManager:
        autowire: true
        autoconfigure: true
        public: true
        calls:
            - [setTemplating, ['@templating']]

    ToolboxBundle\Manager\AreaManagerInterface: '@ToolboxBundle\Manager\AreaManager'
    ToolboxBundle\Manager\AreaManager:
        autowire: true
        autoconfigure: true
        public: false

    ToolboxBundle\Manager\ConfigManagerInterface: '@ToolboxBundle\Manager\ConfigManager'
    ToolboxBundle\Manager\ConfigManager:
        public: true
        autowire: true
        public: true

    ToolboxBundle\Manager\AdaptiveConfigManagerInterface: '@ToolboxBundle\Manager\AdaptiveConfigManager'
    ToolboxBundle\Manager\AdaptiveConfigManager:
        parent: ToolboxBundle\Manager\ConfigManager
        autowire: true
        public: false

