services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # toolbox installer
    ToolboxBundle\Tool\Install: ~

    # toolbox service configuration
    ToolboxBundle\Service\ConfigManager: ~