services:

    # twig extensions
    ToolboxBundle\Twig\Extension\AreaBlockConfigExtension:
        autowire: true
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\DownloadExtension:
        autowire: true
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\DocumentTagExtension:
        parent: Pimcore\Twig\Extension\DocumentTagExtension
        autowire: true
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\DataAttributesExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\LayoutExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    ToolboxBundle\Twig\Extension\ImageThumbnailExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }
