services:

    # toolbox installer
    toolbox.installer:
        class: ToolboxBundle\Tool\Install

    # toolbox services
    toolbox.config_manager:
        class: ToolboxBundle\Service\ConfigManager
        arguments: []
        public: false

    toolbox.area_manager:
        class: ToolboxBundle\Service\AreaManager
        arguments:
            - '@toolbox.config_manager'
            - '@pimcore.area.brick_manager'
        public: false

    toolbox.brick_config_builder:
        class: ToolboxBundle\Service\BrickConfigBuilder
        shared: false
        arguments:
            - '@pimcore.translator'
            - '@pimcore.templating.tag_renderer'
            - '@templating'

    # toolbox bundle connector
    toolbox.connector.bundle:
        class: ToolboxBundle\Connector\BundleConnector
        arguments:
            - '@pimcore.extension.bundle_manager'

    # twig extensions
    toolbox.twig.extension.areablock_configuration:
        class: ToolboxBundle\Twig\Extension\AreaBlockConfigExtension
        public: false
        arguments:
            - '@toolbox.config_manager'
            - '@toolbox.area_manager'
        tags:
            - { name: twig.extension }

    toolbox.twig.extension.download:
        class: ToolboxBundle\Twig\Extension\DownloadExtension
        public: false
        arguments:
            - '@toolbox.config_manager'
            - '@toolbox.connector.bundle'
            - '@pimcore.translator'
        tags:
            - { name: twig.extension }

    toolbox.twig.extension.document_tag_extender:
        class: ToolboxBundle\Twig\Extension\DocumentTagExtension
        public: false
        parent: pimcore.twig.extension.document_tag
        tags:
            - { name: twig.extension }

    toolbox.twig.extension.data_attributes_generator:
        class: ToolboxBundle\Twig\Extension\DataAttributesExtension
        public: false
        arguments:
            - '@toolbox.config_manager'
        tags:
            - { name: twig.extension }

    # base brick
    toolbox.area.brick.base_brick:
        abstract:  true
        calls:
            - [setConfigManager, ['@toolbox.config_manager']]

    # column calculator
    toolbox.calculator.bootstrap3.column:
        class: ToolboxBundle\Calculator\Bootstrap3\ColumnCalculator
        public: false

    # slide column calculator
    toolbox.calculator.bootstrap3.slide_column:
        class: ToolboxBundle\Calculator\Bootstrap3\SlideColumnCalculator
        public: false