imports:
    - { resource: services/*.yml }

services:

    # toolbox installer
    toolbox.installer:
        class: ToolboxBundle\Tool\Install

    # toolbox service configuration
    toolbox.config_manager:
        class: ToolboxBundle\Service\ConfigManager
        public: false

    # toolbox service layout
    toolbox.layout_manager:
        class: ToolboxBundle\Service\LayoutManager
        arguments:
            - '@toolbox.config_manager'
        calls:
            - [setTemplating, ['@templating']]

    # toolbox service area
    toolbox.area_manager:
        class: ToolboxBundle\Service\AreaManager
        arguments:
            - '@toolbox.config_manager'
            - '@pimcore.area.brick_manager'
        public: false

    # toolbox service brick configuration builder
    toolbox.brick_config_builder:
        class: ToolboxBundle\Service\BrickConfigBuilder
        shared: false
        arguments:
            - '@pimcore.translator'
            - '@pimcore.templating.tag_renderer'
            - '@templating'

    # toolbox bundle connector
    toolbox.connector.bundle:
        class: ToolboxBundle\Connector\BundleConnector
        arguments:
            - '@pimcore.extension.bundle_manager'

    # base brick
    toolbox.area.brick.base_brick:
        abstract:  true
        calls:
            - [setConfigManager, ['@toolbox.config_manager']]
            - [setBrickConfigBuilder, ['@toolbox.brick_config_builder']]
            - [setLayoutManager, ['@toolbox.layout_manager']]

    # column calculator
    toolbox.calculator.bootstrap3.column:
        class: ToolboxBundle\Calculator\Bootstrap3\ColumnCalculator
        public: false

    # slide column calculator
    toolbox.calculator.bootstrap3.slide_column:
        class: ToolboxBundle\Calculator\Bootstrap3\SlideColumnCalculator
        public: false