toolbox:
    disallowed_subareas:
        accordion:
            disallowed:
                - accordion
                - container
                - slideColumns
                - parallaxContainer
        columns:
            disallowed:
                - container
                - parallaxContainer
        slideColumns:
            disallowed:
                - slideColumns
                - accordion
                - container
                - parallaxContainer
                - columns
                - anchor
        container:
            disallowed:
                - container
                - parallaxContainer
        parallaxContainer:
            disallowed:
                - container
                - parallaxContainer
        image:
            disallowed:
                - parallaxContainer
        snippet:
            disallowed:
                - parallaxContainer

    disallowed_content_snippet_areas:
        - parallaxContainer
        - teaser
        - container
        - snippet