imports:
    - { resource: areas/*.yml }
    - { resource: theme.yml }
    - { resource: data_attributes.yml }
    - { resource: ckeditor/config.yml }
    - { resource: document/editables.yml }

toolbox:
    image_thumbnails:
        gallery_element: 'galleryImage'
        gallery_lightbox: 'contentImage'
        gallery_thumbnail: 'galleryThumb'
        image_element: 'contentImage'
        image_lightbox: 'lightBoxImage'
        video_poster: 'videoPoster'
        video_thumbnail: 'content'
        teaser_element: 'standardTeaser'
        teaser_lightbox: 'lightBoxImage'
        parallax_background: 'parallaxBackground'
        parallax_section_background: 'parallaxSectionBackground'
        parallax_container_element: 'parallaxImage'
        download_preview_thumbnail: 'downloadPreviewImage'

    disallowed_subareas:
        accordion:
            disallowed:
                - accordion
                - container
                - slideColumns
                - parallaxContainer
        columns:
            disallowed:
                - container
                - parallaxContainer
        slideColumns:
            disallowed:
                - slideColumns
                - accordion
                - container
                - parallaxContainer
                - columns
                - anchor
        container:
            disallowed:
                - container
                - parallaxContainer
        parallaxContainer:
            disallowed:
                - container
                - parallaxContainer
        image:
            disallowed:
                - parallaxContainer
        snippet:
            disallowed:
                - parallaxContainer

    disallowed_content_snippet_areas:
        - parallaxContainer
        - teaser
        - container
        - snippet

    area_block_configuration:
        toolbar:
            title: Inhaltsbausteine
            width: 200
            x: 10
            y: 125
            buttonWidth: 200
        groups: ~