imports:
    - { resource: areas/*.yml }
    - { resource: ckeditor/config.yml }
    - { resource: document/editables.yml }

toolbox:

    disallowedSubAreas:
        accordion:
            disallowed:
                - accordion
                - container
                - slideColumns
                - parallaxContainer
        columns:
            disallowed:
                - container
                - parallaxContainer
        slideColumns:
            disallowed:
                - slideColumns
                - accordion
                - container
                - parallaxContainer
                - columns
                - anchor
        container:
            disallowed:
                - container
                - parallaxContainer
        parallaxContainer:
            disallowed:
                - container
                - parallaxContainer
        image:
            disallowed:
                - parallaxContainer
        snippet:
            disallowed:
                - parallaxContainer

    disallowedContentSnippetAreas:
        - parallaxContainer
        - teaser
        - container
        - snippet

    areaBlockConfiguration:
        toolbar:
            title: Inhaltsbausteine
            width: 200
            x: 10
            y: 125
            buttonWidth: 200
        groups: ~

    enableAssetHandler: false